name: Jupyter Book Website

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: write
  pull-requests: write

jobs:
  jupyter-book:
    runs-on: ubuntu-latest
    env:
      NPROC: '2'
      JULIA_CACHE: '2'
    container:
      image: ghcr.io/sosiristseng/juliabook:1.9.0rc2
      env:
        JULIA_NUM_THREADS: 'auto'
        JULIA_CONDAPKG_BACKEND: 'Null' # Let PythonCall use built-in python
        GKSwstype: 100
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache Julia dependencies
        uses: actions/cache@v3
        if: ${{ env.JULIA_CACHE != '0'}}
        with:
          path: ~/.julia
          key: ${{ runner.os }}-julia-${{ env.JULIA_CACHE }}-${{ hashFiles('*.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-${{ env.JULIA_CACHE }}-
      - name: Install Julia dependencies
        run: JULIA_PROJECT="@." julia --color=yes  -e 'import Pkg; Pkg.Registry.update(); Pkg.instantiate(); Pkg.resolve(); Pkg.precompile()'
      - name: Build notebooks with ${{ env.NPROC }} process(es)
        run: JULIA_PROJECT="@." julia --color=yes -p ${{ env.NPROC }} literate.jl
      - name: Build website
        run: jupyter-book build docs/
      - name: Copy binder environment
        run: |
          cp Project.toml *.txt docs/_build/html/_sources
          cp -R src docs/_build/html/_sources
      - name: Deploy Notebooks
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html/
          force_orphan: true

  binder:
    needs: jupyter-book
    if: ${{ github.ref == 'refs/heads/main' }}
    uses: sosiristseng/jbook-workflows/.github/workflows/binder.yml@main
    with:
        dir: _sources
        ref: gh-pages
